provider:
    localhost:
        cores: auto
workflow:
  - name: check_files
    command: ls -alp

  - name: do_gridsearch
    command: echo '@alpha @beta @mode'
    depends: [check_files]
    param_grid:
      alpha: [0.05, 0.10, 0.15]
      beta: [50, 100, 150]
      mode: [linear, quadratic]

  # It doesn't make sense to put params in a task that it will not use
  # the params in the command to execute
  - name: show_process
    command: ps -eal > process.txt
    depends: [do_gridsearch]
    param_grid:
      gamma: [1, 10]
      beta: [50, 100, 150]
      mode: [linear, quadratic]

  - name: show_hardware
    command: lspci > hardware.txt
    depends: [do_gridsearch]

  - name: create_sysinfo
    command: lsb_release -a > info.txt
    depends: [check_files]

  - name: manage_cats
    command: echo 'cats' > cats.txt
    depends: [create_sysinfo]

  - name: manage_dogs
    command: echo 'dogs' > dog.txt
    depends: [create_sysinfo]

  - name: final_results
    command: ls -alp
    depends: [manage_cats, manage_dogs, show_hardware, show_process]
